### ISSUE TITLE
Links are in HTTP, they should be by HTTPS by default

### ISSUE THREAD

**Issue by poccouy** [approach0/search-engine#13]

**Comment by t-k-** [comment]
Where are the links you are referring to?

**Comment by occouy2** [comment]
@t-k- I'm talking about the links that are presented when a search is made

**Comment by t-k-** [comment]
why is it necessary?

**Comment by poccouy2** [comment]
@t-k- Not enabling https by default is a potential security vulnerability. For example, if one is connected to stackexchange, and then gets to an http version of the site, an attacker may make a man-in-the-middle attack.

It's not necessary. But it's definitely much better and not something difficult to implement. (Open up the urls with notepad++ and replace http:// with https:// automatically)

**Comment by t-k-** [comment]
@poccouy2 I think MSE is using mostly http, by that I mean MSE will not force you to any https link of its posts. And most likely Google also will give you http links of MSE. As search engine. First I think it is not a expected behavior to change the original links crawled and read from MSE. Second I think there are people want trade off security for fast loading, especially for sites not exchanging very important data like MSE or people living out side of US with a slow Internet access like my situation right now.

I will close this issue but welcome other opinion from people. 

Sorry for my late reply.

**Comment by lmffeexd** [comment]
I'm leaving this here because it is somewhat related: [A specific rule has been created for your website](https://github.com/EFForg/https-everywhere/pull/7642) so that users of the HTTPS-Everywhere plugin will always be redirected to the HTTPS version of your website, even if an attacker tries to MiTM and redirect to an HTTP version.

**Comment by t-k-** [comment]
@lmffeexd Approach0 does have HTTPS as default, it is the links that Approach0 directs users to are currently HTTP. This does not affect Google to rank Approach0 as HTTPS site. Just like Google homepage is in HTTPS, but Google will nevertheless direct you to HTTP site if your query hits that site.

**Comment by t-k-** [comment]
"starting to use HTTPS as a ranking signal" does not mean the search results are all HTTPS links. It just means Google is presumably prioritizing HTTPS sites in search result.

**Comment by lmffeexd** [comment]
@t-k-  Yes, I mentioned that only to show that the current trend in the web is to move all traffic to HTTPS. Soon, Firefox and Chrome will start disabling some features for HTTP websites.

**Comment by lmffeexd** [comment]
@t-k- 

> I think MSE is using mostly http, by that I mean MSE will not force you to any https link of its posts. 

This has changed, now all SE links will go to HTTPS https://meta.stackexchange.com/questions/292058/network-wide-https-its-time

I think it's time now for you to reconsider applying this enhancement suggestion.

**Comment by t-k-** [comment]
@lmffeexd Thank you for bringing up this news.

Now I still do not think it is time to switch to all-https, based on the following reasons:

I am against the idea to force https by manually replacing all http prefix to https in search results. This may be simple to do, however, it does not obey search engine principle, and it is not elegant obviously. That being said, if we switch to crawling https://math.stackexchange.com instead, crawler will save hyperlinks in https but it takes more time to crawl https pages and consequently we may need to re-crawl all document on MSE. I have to mention again that I am maintaining this project in my part-time, crawler is running on a single laptop and network is slow.

Second, approach0.xyz itself is in https, so Google will treat approach0.xzy as https site. Besides, there is no obvious security reason to switch to https search results for a math QA website search engine.
