### ISSUE TITLE
Redirect

### ISSUE THREAD

**Issue by kingW3** [approach0/search-engine#20]
Visiting http:\\approach.xyz  doesn't redirect to https:\\approach0.xyz\search instead it downloads a file called download with the following content (Chrome)
```
<?php
header("HTTP/1.1 301 Moved Permanently");
header("Location: https://approach0.xyz/search/");
?>
```
While in IE it just displays the page with plaint text from above.

**Comment by t-k-** [comment]
@kingW3  Thank you for reporting. 

Issue fixed. Recently I am doing some experiment on my VPS, and http to https rewrite rule is removed on purpose, the problem you see is because my `/` to `/search/` redirection page is in PHP and no PHP handler rule is written in http section of NGINX configuration file.
